### PR TITLE
Fix paraglider controller crash during resource creation, by adding additional validation checks.

### LINKED ISSUE #350: Paraglider controller crashes when creating a resource.
When I (mistakenly) create a resource providing its description json using a different cloud provider, the controller crashes with a runtime error of nil pointer dereference or index out of range.

I am using the following json file to startup the controller with:

```
server:
  host: "localhost"
  port: 8080
  rpcPort: 8081

cloudPlugins:
  - name: "gcp"
    host: "localhost"
    port: 8082

  - name: "ibm"
    host: "localhost"
    port: 8083

  - name: "azure"
    host: "localhost"
    port: 8084

tagService:
  host: "localhost"
  port: 8085

namespaces:
  default:
    - name: "gcp"
      deployment: "projects/<ID>"
    - name: "ibm"
      deployment: "/resourcegroup/<ID>"
    - name: "azure"
      deployment: "/subscriptions/<ID>/resourceGroups/<ID>"

```

and the following vm json files (taken from Quickstart manual):

IBM

```
{
    "InstancePrototype": {
        "profile": {
            "name": "bx2-2x8"
        },
        "image": {
            "id": "r014-0acbdcb5-a68f-4a52-98ea-4da4fe89bacb"
        },
        "zone": {
            "name": "us-east-1"
        }
    }
}

```

Azure

```
{
    "location": "eastus",
    "properties": {
        "hardwareProfile": {
            "vmSize": "Standard_B1s"
        },
        "osProfile": {
            "computerName": "sample-compute",
            "adminUsername": "weit",
            "adminPassword": "******"
        },
        "storageProfile": {
            "imageReference": {
                "offer": "0001-com-ubuntu-minimal-jammy",
                "publisher": "canonical",
                "sku": "minimal-22_04-lts-gen2",
                "version": "latest"
            }
        }
    }
}

```

GCP

```
{
    "instance_resource": {
        "disks": [{
            "auto_delete": true,
            "boot": true,
            "initialize_params": {
                "disk_size_gb": 10,
                    "source_image": "projects/debian-cloud/global/images/family/debian-10"
                },
            "type": "PERSISTENT"
        }],
        "machine_type": "zones/us-west1-a/machineTypes/f1-micro"
    },
    "zone": "us-west1-a"
}

```

The below the commands fail along with controller crash:

`glide resource create azure my-vm ibm_vm.json`
`glide resource create azure my-vm gcp_vm.json`
`glide resource create gcp my-vm ibm_vm.json`
`glide resource create gcp my-vm azure_vm.json`

### PR DESCRIPTION
**Pull request by aviweit**
Hi,

This PR aims to fix #350.

I tested it on my local environment and it seems to work well.

Can you please review?

Thanks.

### CODE REVIEW

**Review by praveingk — APPROVED** [review]
Looks good to me. @seankimkdy @smcclure20 Please check.

**Comment by aviweit** [comment]
@praveingk , I would like to ask whether this PR can be merged? Thanks.

**Comment by praveingk** [comment]
> 

@aviweit  Waiting on https://github.com/paraglider-project/paraglider/pull/403 to be merged, and please rebase once done. This would enable functional tests approval on forked PRs.

**Comment by seankimkdy** [comment]
#403 was merged but having some errors. Hang tight and I'll update once these errors are fixed.

**Comment by seankimkdy** [comment]
@aviweit issue is fixed. Please try merging with main to get the latest checks.

**Comment by aviweit** [comment]
> @aviweit issue is fixed. Please try merging with main to get the latest checks.

@seankimkdy , I merged and it seems that the checks passed. Thanks.

**Pull request merged**
